jobs:
  - name: slack-tester
    type: runSh
    steps:
      - TASK:
        - script: echo "this should generate a message and the destination room"
        - script: echo "that it will pass to the slack-service"
        - script: echo "slack-service will send it to the room specified"
        - script: echo "test template message" > $JOB_STATE/slack-tester.env
        - script: echo "copied sample text to $JOB_STATE/slack-tester.env"


  - name: slack-service
    type: runSh
    steps:
      - IN: slack-tester
      - IN: slack-service-repo
      - TASK:
        - script: echo "running slack service runSh\n"

        - script: echo 'cat "IN/slack-tester/runSh/slack-tester.env"'
        - script: cat "IN/slack-tester/runSh/slack-tester.env"

        - script: echo '\nls "IN/slack-tester/runSh"'
        - script: ls "IN/slack-tester/runSh"

        - script: echo "\nRunning scipt"
        - script: bash IN/slack-service-repo/gitRepo/script.sh

        - script: echo "sleeping for 4 min"
        - script: sleep 240
