jobs:
  - name: slack-tester
    type: runSh
    steps:
      - IN: mesg-and-token
      - IN: slack-test-repo
        switch: off
      - TASK:
        - script: cd IN/slack-test-repo/gitRepo && ./slack-tester-runsh.sh

  - name: slack-service
    type: runSh
    steps:
      - IN: slack-tester
      - IN: slack-service-repo
        switch: off
      - IN: slack-test-repo
        switch: off
      - TASK:
        - script: cd IN/slack-test-repo/gitRepo && ./slack-service-runsh.sh
