jobs:
  - name: slack-tester
    type: runSh
    steps:
      - TASK:
        - script: echo "this should generate a message and the destination room"
        - script: echo "that it will pass to the slack-service"
        - script: echo "slack-service will send it to the room specified"
        - script: echo "test template message" > $JOB_STATE/slack-tester.env
        - script: echo "copied sample text to $JOB_STATE/slack-tester.env"


  - name: slack-service
    type: runSh
    steps:
      - IN: slack-tester
      - TASK:
        - script: echo "running slack service runSh 2"
        - script: echo "JOB_STATE $JOB_STATE"
        - script: echo "message from slack-tester"
        - script: cat "IN/slack-tester/runSh/slack-tester.env"
        - sciprt: ls "IN/slack-tester/runSh"
        - sciprt: sleep 240
